blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using stormfinder
    url: https://github.com/darshakkanani/stormfinder/discussions/categories/q-a
    about: Ask a question or request support for using stormfinder

  - name: Share idea / feature to discuss for stormfinder
    url: https://github.com/darshakkanani/stormfinder/discussions/categories/ideas
    about: Share idea / feature to discuss for stormfinder

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/darshakkanani
    about: Connect with PD Team for direct communication